# Generated by Django 5.0.1 on 2024-01-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_term_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermcourse',
            name='images',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='photos/courses'),
        ),
    ]
